version: "2.0"

services:
  user:
    image: aryel/technical-evaluation-user
    ports:
      - "8080:8080"
  credit:
    image: aryel/technical-evaluation-credit-check
    ports:
      - "8081:8081"
    depends_on:
      - user
    environment:
      COM_TECHNICAL_EVALUATION_USER_SERVER_HOST: user
##  nginx:
##    image: nginx
##    ports:
##      - "80:80"
##    volumes:
##      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
##      - "./technical-evaluation-webapp:/var/www/html"
##    depends_on: 
##      - user
##      - credit  
