server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    url: jdbc:h2:mem:calcard
    username: root
    password: root
    driver-class-name: org.h2.Driver    
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true